services:
  scoring-api:
    image: redteamsubnet61/rest-scoring-api:4.2.0-260910
    build:
      context: .
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      RT_SCORING_API_PORT: ${RT_SCORING_API_PORT:-8090}
      RT_SCORING_API_POLL_INTERVAL: ${RT_SCORING_API_POLL_INTERVAL:-1200}
      RT_SCORING_API_CORE_API_URL: ${RT_SCORING_API_CORE_API_URL:-http://localhost:8000/api/v1}
      RT_SCORING_API_CORE_API_KEY: ${RT_SCORING_API_CORE_API_KEY}
    env_file:
      - path: .env
        required: false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "${RT_SCORING_API_PORT:-47920}:${RT_SCORING_API_PORT:-47920}"
    tty: true
