[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf


################### REST SCORING API JSON LOGS ###################
[INPUT]
    Name              tail
    Path              /var/log/rest-scoring-api/json/*.all.json.log
    Path_Key          filepath
    Tag               rest-scoring-api.json
    Parser            scoring_json
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Read_from_Head    On
    Ignore_Older      1h
    Refresh_Interval  10
    Rotate_Wait       30


################### OUTPUT TO STACK-REDTEAM LOKI ###################
[OUTPUT]
    Name    loki
    Match   rest-scoring-api.json
    Host    10.178.0.3
    Port    3100
    Uri     /loki/api/v1/push
    Labels  job=rest-scoring-api,log_type=json,
